name = "mesagisto-center-cfworker"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "cargo install -q worker-build --target=x86_64-unknown-linux-musl && worker-build --release"
